/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppNavbar: typeof import('./src/components/app-navbar.vue')['default']
    PaginatedTable: typeof import('./src/components/paginated-table.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UApp: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UAvatar: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Avatar.vue')['default']
    UBreadcrumb: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Breadcrumb.vue')['default']
    UButton: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCard: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Card.vue')['default']
    UDropdownMenu: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/DropdownMenu.vue')['default']
    UForm: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Form.vue')['default']
    UFormField: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/FormField.vue')['default']
    UIcon: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    ULink: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/vue/components/Link.vue')['default']
    UNavigationMenu: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPagination: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Pagination.vue')['default']
    UPopover: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Popover.vue')['default']
    USelect: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USkeleton: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Skeleton.vue')['default']
    UTable: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Table.vue')['default']
    UTabs: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Tabs.vue')['default']
    UTooltip: typeof import('./../node_modules/.pnpm/@nuxt+ui@3.2.0_@babel+parser@7.28.0_axios@1.10.0_embla-carousel@8.6.0_encoding@0.1.13_t_66bfc0833bedb32532d69c04bd7cad8d/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
